trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  nodeVersion: "22.x"
  # Replace with your Azure Static Web App name
  staticWebAppName: "testpipelinefrontend"
  # Remove the hardcoded token for security

stages:
  - stage: Deploy
    displayName: "Deploy to Azure Static Web App"
    jobs:
      - job: Deploy
        displayName: "Deploy to Azure Static Web App"
        steps:
          - task: AzureStaticWebApp@0
            inputs:
              app_location: '.'
              api_location: ''
              output_location: 'dist'
              azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'

