trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

variables:
  nodeVersion: "22.x"
  # Replace with your Azure Static Web App name
  staticWebAppName: "testpipelinefrontend"
  - group: "TestProject"

stages:
  - stage: Deploy
    displayName: "Deploy to Azure Static Web App"
    jobs:
      - job: Deploy
        displayName: "Deploy to Azure Static Web App"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '$(nodeVersion)'
            displayName: 'Install Node.js'

          # ✅ Inject VITE_API_URL into a .env file for Vite to pick up
          - script: |
              echo "VITE_API_URL=$VITE_API_URL" >> .env
              cat .env
            displayName: "Create .env file with VITE_API_URL"

          - task: AzureStaticWebApp@0
            inputs:
              app_location: '.'
              api_location: ''
              output_location: 'dist'
              azure_static_web_apps_api_token: '$(AZURE_STATIC_WEB_APPS_API_TOKEN)'

